VAGRANTFILE_API_VERSION = "2"

name = "pilot"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "docker" do |d|

    d.name = name

    d.build_dir = "."
    d.build_args = ["--tag", name]

    d.has_ssh = true
    d.remains_running = true

    d.cmd = ["/usr/sbin/sshd", "-D"]

  end

  config.ssh.username = "root"
  config.ssh.password = "root"

end
